name: crawl-all-hourly
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Supabase
        run: |
          curl --request GET \
          --url 'https://tweetic.io/api/crawl-all?keyword=supabase' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - run: sleep 10
      - name: Nuxt
        run: |
          curl --request GET \
          --url 'https://tweetic.io/api/crawl-all?keyword=nuxt' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
